version: '3'
networks:
  rasagul:

services:
  rasaserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: rasagul/army
    container_name: rasaserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    depends_on:
      - rasaapp    
    volumes:
     - ./:/var/www
     - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - log_storage:/var/log/data 
    networks:
      - rasagul 
  rasaapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: rasagul/example  
    container_name: rasaapp
    volumes:
      - ./:/var/www
      - ./:/var/www/storage/logs/
    ports:
      - "9008:9000"
    networks:
      - rasagul    
volumes: 
  log_storage:  
